name: Build Android APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip Project Files
        run: |
          unzip Asset.zip -d project_extracted
          # मुख्य डायरेक्टरी को सही जगह सेट करने के लिए
          if [ -d "project_extracted/nexfile_manager_flutter" ]; then
            mv project_extracted/nexfile_manager_flutter/* .
            mv project_extracted/nexfile_manager_flutter/.* . 2>/dev/null || true
          else
            mv project_extracted/* . 2>/dev/null || true
          fi

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
